version: '3'
services:
  db_postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: mentorq-api
      POSTGRES_DB: mentorq
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-production
    restart: always
    links:
      - db_postgres
  prod:
    build: ./prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prod/build:/usr/share/nginx/html:ro
      - /var/lib/dehydrated/certs:/var/lib/dehydrated/certs:ro
    restart: always
    links:
      - api
