version: '3'
services:
  db_postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: mentorq-api
      POSTGRES_DB: mentorq
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
  api:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - db_postgres
    restart: always
  # web_client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - api
