version: '3'
services:
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  db_postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: mentorq-api
      POSTGRES_DB: mentorq
    logging:
      driver: none
  api:
    build: ./api
    ports:
      - "8080:8080"
    links:
      - db_mongo
  # web_client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - api
